### ISSUE TITLE
top-level elm-stuff must be cleaned after installing a new test dependency

### ISSUE THREAD

**Issue by avh4** [rtfeldman/node-test-runner#145]
When I add a new dependency to my `tests/elm-package.json`, when I run `elm-test` after that, I get an error that the package doesn't exist:

```
$ (cd tests; elm-package install --yes rtfeldman/elm-css-helpers)
$ elm-test
Success! Compiled 90 modules.
Successfully generated /dev/null
Could not find package rtfeldman/elm-css-helpers.

Maybe your elm-stuff/ directory has been corrupted? You can usually fix stuff
like this by deleting elm-stuff/ and rebuilding your project.
Compilation failed for /Users/.../myproject/elm-stuff/generated-code/elm-community/elm-test/src/Main496aafb3c4c5cf7d1e284a81de8ccea9.elm
```

```
$ elm-test --version
0.18.3
```

Deleting `./tests/elm-stuff` doesn't change anything, but deleting `./elm-stuff` does resolve the error.

**Comment by rtfeldman** [comment]
I have a vague idea how to fix this (copying things from the tests' `elm-stuff` into the root `elm-stuff`) but I'm not sure how to do it automatically without offering a command like `elm-test install rtfeldman/elm-css-helpers` which would both install the dependency and do the `elm-stuff` copying.

I think that's a reasonable feature to add, given that in a world where `elm-package.json` has a `test-depdendencies` field instead of tests having a separate `elm-package.json`, we'd want such a feature anyway.

Another possibility might be to uncritically copy the entire contents of `tests/elm-stuff` into the root `elm-stuff` every time `elm-test` runs, but that would be pretty slow and wasteful. 😬

**Comment by avh4** [comment]
Why is elm-test even using the top-level elm-stuff folder?  Can it just put everything in `tests/elm-stuff` ?
