### ISSUE TITLE
[discussion] This was a pretty painful upgrade

### ISSUE THREAD

**Issue by zwilias** [rtfeldman/node-test-runner#151]
# Problem statement

0.18.2 -> 0.18.3/4 is proving to be a pretty painful upgrade; and I'd like to try and gather some ideas on preventing this in future releases.

## Pre-release

- people were installing `elm-community/elm-test` through `elm-package` which means they got the 4.0.0 version _before_ `node-test-runner` was released fully. I know that this is hard/impossible to properly prevent, but it's something to think about.

## Post-release

- Travis tests unexpectedly breaking because `elm-test` wasn't pinned in `package.json`
- Lots of confusion about how to upgrade tests
- Breakage due to packages depending on `elm-test` not being upgraded

# How to deal with this

So perhaps something that could _help_ is having some sort of release checklist that should contain at least a subset of the following:

- [ ] Check impact on related packages
  - [ ] elm-doc-test
  - [ ] elm-html-test
  - [ ] elm-test-bdd-style
  - [ ] […]
- [ ] communication
  - [ ] what changes, why, and how does it impact you as a user
  - [ ] upgrade instructions and/or tooling
  - [ ] centralized, referable release-notes

As a more general thing; one option to prevent this is to have people pin their dependency on `elm-test` in `package.json`. In the long run, this seems undesirable. I know we're mirroring elm versions which means we're at 0.18 and even backwards compatibility breaking upgrades are a patch change, but perhaps this should be reconsidered?

**Comment by avh4** [comment]
I'll add the suggestion of having `elm-test` itself detect when the manual upgrade steps haven't been preformed and giving instructive error messages.

**Comment by iGEL** [comment]
I suggest you [keep a changelog](http://keepachangelog.com/en/0.3.0/). I'm still not sure what changed or where to find a description of changes. Could have saved me some trouble.

**Comment by eeue56** [comment]
> people were installing elm-community/elm-test through elm-package which means they got the 4.0.0 version before node-test-runner was released fully. I know that this is hard/impossible to properly prevent, but it's something to think about.

We did this previous with project-fuzzball: http://package.elm-lang.org/packages/project-fuzzball/node/latest

This is likely the best way to try these experimental releases out.

> Travis tests unexpectedly breaking because elm-test wasn't pinned in package.json

These changes were a _breaking_ change. This is where following upstream's version numbers fall down. We can use [prerelease](https://docs.npmjs.com/misc/semver#prerelease-tags) tags to work around this. E.g I think we can consider `elm-version` a pre-release tag, and therefore use `1.0.0@elm-version.18`. Need to discuss with some upstream people I suspect.


Changes like this require tooling like elm-upgrade IMO. It's worth putting more time into making these releases seemless because it saves us time supporting the upgrade.

**Comment by harrysarson** [comment]
I think we have a better upgrade method now (basically try not to break anything except when the compiler releases a new version) and 4 (!) years have passed so I think we can close.
