### ISSUE TITLE
Stop automatically installing packages?

### ISSUE THREAD

**Issue by rtfeldman** [rtfeldman/node-test-runner#239]
For a long time, running `elm-test` has automatically run `elm-package install` whenever you run tests. Assuming this is not necessary for any technical reason (which I believe it currently is not), should we do it?

@tjarratt commented:

> 99% of the time I'm running tests and it is unnecessary to install packages (because they are already installed), so this feels like a bit of a net loss to me (personally), since now elm-test knows about running tests AND about possibly needing to install packages ? I'd be really, really curious about the design decision for this and understanding why elm-test needs to try to install packages when there is already a perfectly good command that does that.

My default thinking is "Yes, let's stop automatically installing packages." It's one less step to run, so tests will run slightly faster, and with the way things are set up now, I wouldn't expect it to break anything.

Can anyone think of downsides?

**Comment by BrianHicks** [comment]
On a developer machine, nbd. But, this change may break people’s CI setups unexpectedly. If they’re using the latest, suddenly they will need another step to install packages. Arguably they should be doing that anyway, but it’s still a breaking change.

**Comment by eeue56** [comment]
I commented on Slack, but right now, with how elm-package works, I'm a massive 👎 👎 

If you run `elm-make` with packages installed, but a new package version has been released that matches your criteria, the new version won't be installed unless you run `elm-package install`. This means that the test dependencies can fall completely out of sync with your main dependencies.

For example:

```
elm-package install --yes elm-lang/core 5.0.0
-- set bounds to 5.0.0 <= v < 6.0.0 to reproduce reality
-- core is still 5.0.0
elm-make <blah>
-- core is still 5.0.0
elm-package install --yes
-- core is 5.1.1
```

Likewise, if you run elm-test but forget to add `elm-package install`, which is very very easily done, since initial `elm-make` will install packages, then subsequent builds on CI will fail. So right now, with the current state of elm-package and elm-package.json, I would be for a big 👎 

These reasons are why it was added in the first place: https://github.com/rtfeldman/node-test-runner/pull/183

**Comment by BrianHicks** [comment]
What if it looked at the actual dependencies vs the desired ones, and only ran the install to correct the delta?

👍: faster in the common case
👍: CI doesn’t break
👎: elm-test still knows about package management

**Comment by muelli** [comment]
I think I'm tripping over a package management issue.

In my CI I'm caching `node_modules`, `elm-stuff`, and `tests/elm-stuff`. I've added a dependency in elm-package.json and my CI fails, because elm-test can't find the new package. And I seem to be unable to tell elm-test to reinstall packages. I also can't install packages manually, because I don't know how to. Now I have to clear out all the caches, for elm-test to be happy again.

**Comment by mgold** [comment]
@muelli Please open a new issue.

**Comment by harrysarson** [comment]
This issue is relevant to the old (0.18.0) setup where running tests requires an `elm-package.json` file in a nested directory. With the 0.19.0 release I believe this is resolved!
