### ISSUE TITLE
"beforeEach block" for descriptions

### ISSUE THREAD

**Issue by fonzerelly** [rtfeldman/node-test-runner#240]
Hi,
I have been working with elm-test now for a month but I am still new to elm. elm-test is great completion of the elm language. But before I have been working with jasmine a lot and I am used to set up mock variables and the like in a beforeEach-Block of a describe-block that bundles related tests together.

In elm-test, there is as far I can tell not beforeEach-function. Instead, I worked until now with let ... in - statements to define such variables in the beginning of the test suite or in each test itself.

Unfortunatelly, this does not allow me to define variables per describe-block. 

So my question is: Would it make sense to define describe in a way that it takes a function instead of an array of test calls, so that you can define let .. in statements inside of it? Or would it be possible to create a beforeEach-function, that I could combine to the tests in the array of description?

Thanks a lot for your feedback.

**Comment by zwilias** [comment]
`let .. in` is just an expression that introduces variable bindings that are only scoped to what following after `in`, so you can actually already use this to set up such variables:

```elm
suite : Test
suite =
    describe "suite"
        [ describe "part A" <|
            let
                foo : String
                foo =
                    "hello"

                bar : String
                bar =
                    "world"
            in
            [ test1 foo
            , test2 bar
            , test3 foo bar
            ]
        ,  describe "part B" <|
            let
                foo : String
                foo =
                    "don't"

                bar : String
                bar =
                    "worry"
            in
            [ test1 foo
            , test2 bar
            , test3 foo bar
            ]
        ]

test1 : String -> Test
test2 : String -> Test
test3 : String -> String -> Test
```

In this specific case, that means repeating a bunch of stuff so that could be factored out, while also making it a bunch clearer that the "parts" are variations of the same set of tests with different data.

```elm
suite : Test
suite =
    describe "suite"
        [ part "part A" { foo = "hello", bar = "world" }
        , part "part B" { foo = "don't", bar = "worry" }
        ]


part : String -> { foo : String, bar : String } -> Test
part description { foo, bar } =
    describe description
        [ test1 foo
        , test2 bar
        , test3 foo bar
        ]
```

I hope this helps! If you feel like you could use more guidance, I heavily recommend asking around on [slack][slack], [discourse][discourse] or [reddit][reddit]!

[slack]: https://elmlang.herokuapp.com/
[discourse]: https://discourse.elm-lang.org
[reddit]: https://www.reddit.com/r/elm/

**Comment by rtfeldman** [comment]
Gonna close this, since I think @zwilias addressed it. Thanks!
