### ISSUE TITLE
elm-test can be tricked into generating invalid dependencies

### ISSUE THREAD

**Issue by ianmackenzie** [rtfeldman/node-test-runner#277]
If `elm.json` has too-wide dependency ranges, it is possible that building normally with `elm make` will work but running the tests with `elm-test` will not. For example, consider the following `elm.json`:

```json
{
    "type": "package",
    "name": "ianmackenzie/elm-test-dependencies",
    "summary": "Tricking elm-test into specifying invalid dependencies",
    "license": "MPL-2.0",
    "version": "1.0.0",
    "exposed-modules": [
        "Module"
    ],
    "elm-version": "0.19.0 <= v < 0.20.0",
    "dependencies": {
        "elm/core": "1.0.0 <= v < 2.0.0",
        "ianmackenzie/elm-float-extra": "1.0.0 <= v < 2.0.0"
    },
    "test-dependencies": {
        "elm-explorations/test": "1.0.0 <= v < 2.0.0"
    }
}
```

`ianmackenzie/elm-float-extra` currently only has two versions - 1.0.0 for Elm 0.18 and 1.0.1 for Elm 0.19. `elm make` will end up installing 1.0.1, but the `elm.json` generated by `elm-test` will use a version constraint of 1.0.0 instead. Since that version only exists for Elm 0.18, `elm make` will produce a "The dependencies in your elm.json are not compatible" message, which ends up getting reported by `elm-test` as "got an unexpected result from 'elm make' when validating transitive dependencies".

The fix was to use the correct version range `"ianmackenzie/elm-float-extra": "1.0.1 <= v < 2.0.0"` in the package `elm.json`. This shouldn't happen if `elm install` is used to install dependencies, since it will only set up valid ranges. I only ran into it since I just copied my old `elm-package.json` to `elm.json` and then modified it as necessary. But it seems like a fairly easy mistake to make if for whatever reason you're editing `elm.json` files by hand - I know that on Slack at least @sporto ran into the same issue.

If it helps, I've made [a skeleton project](https://github.com/ianmackenzie/elm-test-dependencies) that reproduces the issue - cloning and running `elm-test` should trigger the "unexpected result" error message, and fixing the dependency constraint as described above should get everything working.

I'm on Windows 10 using `elm-test@0.19.0-beta6`.

**Comment by mgold** [comment]
What's the logic behind using the earlier dependency in the range rather than the latest? Maybe we should fix that?

(In 0.19 applications have fixed versions of their dependencies, while packages have ranges. If application A depends on packages B and C, and B also depends on C, will only one version of C be installed? I'm not sure. Finding out might point us in the right direction for testing B with the appropriate version(s) of C.)

As mentioned, this error only happens when copying an `elm(-package).JSON` file, so I'm not sure how much we should change for this particular issue, but it seems there's a cluster of related issues with dependencies.

**Comment by rtfeldman** [comment]
> What's the logic behind using the earlier dependency in the range rather than the latest? Maybe we should fix that?

Originally this was because it was easier to implement, but after thinking about it a bunch more, choosing the lowest version across the board actually seems like the correct design.

If my dependencies say I am compatible with version `1.0.0` and higher, but in actuality I only work with `1.0.1` and above, this is a good thing for tests to surface! If my tests break as a result of dependency constraints being lower than what actually works, I'd like to know about this so I can bump my constraints. That will prevent the problem from affecting others.

So I think the actual resolution here should be to give a better error message when this happens. Maybe it could say something like this:

```
Your dependency on `ianmackenzie/elm-float-extra` says it works with these versions:

1.0.0 <= v < 2.0.0

However, in practice the lowest version I could find that works is 1.0.1, not 1.0.0.

Try changing it to this instead:

1.0.1 <= v < 2.0.0
```

Thoughts?

**Comment by ianmackenzie** [comment]
Is the implicit argument there that `elm make` at least ensures that a given project **compiles** with the most recent versions of its dependencies, and `elm-test` ensures that everything compiles **and** the tests pass with the oldest possible versions of its dependencies, and the combination of the two gives you reasonably good confidence that everything will work for versions in between? The gold standard would of course to run the tests for _every possible valid combination of dependency versions_ =)

One other point I just thought of: even if I specify individually-valid dependency ranges for my dependencies, it's possible that interdependencies between them could mean that pinning to the lowest bound for each would not work. If I depend directly on `"packageA" : "1.0.0 <= v < 2.0.0"` and `"packageB" : "1.0.0 <= v < 2.0.0"`, but `packageB` has a dependency on `"packageA" : "1.1.0 <= v < 2.0.0"`, then pinning each of them to 1.0.0 will fail. I guess in that case there's no harm in updating my own `elm.json` to have `"packageA" : "1.1.0 <= v < 2.0.0"`, but it seems a bit messy if my package itself doesn't require any of the 1.1 features.

All that said, I suspect a lot of this can wait until `elm-test` is rolled into the official Elm toolset, at which point it will presumably have more direct access to the version resolution algorithm/results that Elm itself uses. In the meantime I think it would be fine to just have some sort of generic error message indicating that there was a dependency resolution problem, maybe list the exact dependency versions tried, and suggest tweaking dependency ranges in `elm.json`.

**Comment by rupertlssmith** [comment]
Was going to paste an elm.json that is failing, but @ianmackenzie 's report already covers the issue I was experiencing.

The proposal from @rtfeldman for a better error message would really help with this. 

Also wondering if the elm-json tool could have an option to automatically fix this by solving and then tightening the ranges.
