### ISSUE TITLE
Diff the package versions in an elm-test folder with the parent folder

### ISSUE THREAD

**Issue by eeue56** [rtfeldman/node-test-runner#28]
`elm-package.json` contains the deps

```
"Apanatshka/elm-signal-extra": "5.7.0 <= v <= 5.7.0",
"circuithub/elm-json-extra": "2.2.0 <= v <= 2.2.0",
"circuithub/elm-list-extra": "3.7.1 <= v <= 3.7.1",
"circuithub/elm-maybe-extra": "1.5.1 <= v <= 1.5.1",
"circuithub/elm-result-extra": "1.3.1 <= v <= 1.3.1",
"elm-lang/core": "3.0.0 <= v <= 3.0.0",
"evancz/elm-effects": "2.0.1 <= v <= 2.0.1",
"evancz/elm-html": "4.0.2 <= v <= 4.0.2",
"evancz/elm-http": "3.0.0 <= v <= 3.0.0",
"evancz/elm-markdown": "2.0.0 <= v < 3.0.0",
"evancz/start-app": "2.0.2 <= v <= 2.0.2",
"NoRedInk/elm-rails": "3.0.0 <= v <= 3.0.0",
"NoRedInk/elm-string-extra": "1.1.1 <= v <= 1.1.1",
"rluiten/mailcheck": "3.0.2 <= v <= 3.0.2",
"rtfeldman/elm-validate": "1.1.1 <= v <= 1.1.1",
```

we should make sure that `test/elm-package.json` contains _at least_ the packages

```
"Apanatshka/elm-signal-extra": "5.7.0 <= v <= 5.7.0",
"circuithub/elm-json-extra": "2.2.0 <= v <= 2.2.0",
"circuithub/elm-list-extra": "3.7.1 <= v <= 3.7.1",
"circuithub/elm-maybe-extra": "1.5.1 <= v <= 1.5.1",
"circuithub/elm-result-extra": "1.3.1 <= v <= 1.3.1",
"elm-lang/core": "3.0.0 <= v <= 3.0.0",
"evancz/elm-effects": "2.0.1 <= v <= 2.0.1",
"evancz/elm-html": "4.0.2 <= v <= 4.0.2",
"evancz/elm-http": "3.0.0 <= v <= 3.0.0",
"evancz/elm-markdown": "2.0.0 <= v < 3.0.0",
"evancz/start-app": "2.0.2 <= v <= 2.0.2",
"NoRedInk/elm-rails": "3.0.0 <= v <= 3.0.0",
"NoRedInk/elm-string-extra": "1.1.1 <= v <= 1.1.1",
"rluiten/mailcheck": "3.0.2 <= v <= 3.0.2",
"rtfeldman/elm-validate": "1.1.1 <= v <= 1.1.1",
```

**Comment by benansell** [comment]
@rtfeldman - what are your thoughts on this enhancement? Is it worth me having a go at an implementation and submitting a PR or are you holding off for "profile" support mentioned in #21?

**Comment by eeue56** [comment]
Already have this implemented here -> https://github.com/NoRedInk/elm-ops-tooling#elm_deps_check

**Comment by eeue56** [comment]
and also here -> https://github.com/eeue56/elm-package-for-production

**Comment by benansell** [comment]
Thanks @eeue56 - from what I can tell the 1st link seems to map directly as a solution to this issue and would just need converting to js and integrating into the test runner. While the 2nd seems closer to the idea of profiles / having this to be added to the core Elm toolchain.

So I suppose my question is did @rtfeldman add a enhancement flag to this issue thinking that the 1st option is the way forward? Otherwise I assume it would of been closed with a comment about it due to be supported elsewhere. 

Personally I would  like it integrated somewhere so that everybody benefits from an automatic dependency check as part of running the tests.
