### ISSUE TITLE
Consider using greenkeeper

### ISSUE THREAD

**Issue by harrysarson** [rtfeldman/node-test-runner#345]
Greenkeeper (https://account.greenkeeper.io) will submit pull requests to update npm dependencies. On projects I have been involved in we have found it very useful for keeping our npm package up to date.

Installation is fairly straight forward but would require @rtfeldman to give greenkeeper the permissions it needs.

**Comment by rtfeldman** [comment]
I checked it out, and the first permission it requires is a deal-breaker for me.

<img width="485" alt="Screen Shot 2019-03-10 at 10 52 54 PM" src="https://user-images.githubusercontent.com/1094080/54097625-6bd0c200-4387-11e9-924f-66ad865b8bf1.png">

If it could only do PRs, that'd be one thing, but I'm not comfortable authorizing arbitrary write access to code, no matter how good Greenkeeper's reputation (currently) might be. I don't want to worry about what happens if an attacker compromises them someday.

Thanks for the idea!

**Comment by harrysarson** [comment]
Makes perfect sense!
