### ISSUE TITLE
High severity vulnerability

### ISSUE THREAD

**Issue by smucode** [rtfeldman/node-test-runner#360]
`npm-audit` reveals `elm-test` has some vulnerable dependencies. Would be nice to get them upgraded so we can get rid of this error:

```
$ npm init -y && npm install --save elm-test && npm audit

...

+ elm-test@0.19.0-rev6
added 378 packages from 208 contributors and audited 2388 packages in 10.462s
found 1 high severity vulnerability
  run `npm audit fix` to fix them, or `npm audit` for details
                                                                                
                       === npm audit security report ===                        
                                                                                
# Run  npm install elm-test@0.19.0  to resolve 1 vulnerability
┌───────────────┬──────────────────────────────────────────────────────────────┐
│ High          │ Arbitrary File Overwrite                                     │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ tar                                                          │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ elm-test                                                     │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path          │ elm-test > fsevents > node-pre-gyp > tar                     │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ More info     │ https://npmjs.com/advisories/803                             │
└───────────────┴──────────────────────────────────────────────────────────────┘


found 1 high severity vulnerability in 2388 scanned packages
  run `npm audit fix` to fix 1 of them.

```

**Comment by avh4** [comment]
The reported path is `elm-test > fsevents > node-pre-gyp > tar`, so it looks like this can be solved by updating `fsevents` to `^1.2.8` (upstream issue: https://github.com/fsevents/fsevents/issues/262)

**Comment by smucode** [comment]
@mgold Possible to get this released? :)

**Comment by mgold** [comment]
@rtfeldman ?

**Comment by harrysarson** [comment]
I don't think all the vulnerabilities have been fixed.

**Comment by rtfeldman** [comment]
Correct - we tried a fix for the `elm` package but the new approach runs into issues with the Windows virus scanner apparently, and I don't want to publish a new version that depends on it until that's resolved.

`elmi-to-json` does not have a fix yet.

**Comment by harrysarson** [comment]
Probably worth reopening this issue then

**Comment by stoeffel** [comment]
fyi. elmi-to-json is fixed.

**Comment by harrysarson** [comment]
See #366!

**Comment by jwoudenberg** [comment]
Just created a PR that upgrades to the latest `node-elm-compiler`: #379

`npm audit` tells me that should be the last of it. Anyone aware of further steps that need to be taken to be able to do a new release?

**Comment by afriestad** [comment]
I cloned master and ran an audit:

```
node-test-runner$ npm install && npm audit

[...]

added 234 packages from 654 contributors and audited 564 packages in 16.035s
found 2 high severity vulnerabilities
  run `npm audit fix` to fix them, or `npm audit` for details
                                                                                
                       === npm audit security report ===                        
                                                                                
# Run  npm update tar --depth 3  to resolve 1 vulnerability
┌───────────────┬──────────────────────────────────────────────────────────────┐
│ High          │ Arbitrary File Overwrite                                     │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ tar                                                          │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ elm [dev]                                                    │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path          │ elm > binwrap > tar                                          │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ More info     │ https://npmjs.com/advisories/803                             │
└───────────────┴──────────────────────────────────────────────────────────────┘


# Run  npm update fstream --depth 4  to resolve 1 vulnerability
┌───────────────┬──────────────────────────────────────────────────────────────┐
│ High          │ Arbitrary File Overwrite                                     │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ fstream                                                      │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ elm [dev]                                                    │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path          │ elm > binwrap > tar > fstream                                │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ More info     │ https://npmjs.com/advisories/886                             │
└───────────────┴──────────────────────────────────────────────────────────────┘


found 2 high severity vulnerabilities in 564 scanned packages
  run `npm audit fix` to fix 2 of them.
```

I see on npm that these vulnerabilities do not appear on end systems, since they no longer depend on `binwrap`. All the other vulnerabilities are gone, and https://github.com/rtfeldman/node-test-runner/issues/369 seems to confirm that `--watch` also works on Windows again.

@avh4 @jwoudenberg @rtfeldman Are there additional issues that need to be resolved, or can the release now be updated?

I also see that a version `0.19.0-rev6` exists on npm but not in github releases, so that could be a gotcha when bumping the version.

**Comment by harrysarson** [comment]
So to fix these vulnerabilities we would need to update elm to `elm@0.19.0-no-deps`.

However, I tried to do this in #378 (see commits https://github.com/rtfeldman/node-test-runner/pull/378/commits/634478e118aa17bca99f4263725aa0de1630a062, https://github.com/rtfeldman/node-test-runner/pull/378/commits/e79d6fa5c097f4855e83a4b0547c8ac626a9fe38 and https://github.com/rtfeldman/node-test-runner/pull/378/commits/ac9264a8dc384c09ae0d4d94ab01a78bcd051bbf for my three failed attempts) but doing so broke our [CI runs on windows](https://ci.appveyor.com/project/rtfeldman/node-test-runner/builds/26622101/job/fh3yxrlnkdqs6s4r). The root cause of the failure is https://github.com/elm/compiler/issues/1967.

@afriestad if you can find a work around that keeps CI green whilst upgrading to the latest elm package on npm then we can go ahead and fix these audit issues.

**Comment by afriestad** [comment]
@harrysarson Where did you find the error that you report in that issue? I can only find ```C:\projects\node-test-runner\tests\ci.js: error: tests\*Fail*.elm: expected tests to fail``` in the CI logs for the commits you linked. I had the same error in another project, which disappeared on its own when I deleted `package-lock.json` and `node-modules`. Perhaps the error is one of caching?

In any case: while the vulnerabilities in `tar` are certainly severe, they seem a bit less so than the others that have been fixed already, since they only come into play if we should unpack a tarball containing a hard link pointing to a file that already exists on the disk, and to which the calling user has write permission (unless I have misunderstood the NPM advisories). Since `elm` is a dev dependency, the problem also does not affect end users (nor dependees?) of `elm-test`.

If updating the `elm` dev dependency seems to trigger an obscure error that will take time to track down and fix, perhaps it would be worthwhile to push a new release now? Especially since the current master contains the fixes to the issue in the OP as well as the issue reported in #369, which are all in production dependencies and affect end users. Releasing a fix for the user-facing vulnerabilities first seems like a good idea to me, at least.

**Comment by harrysarson** [comment]
> @harrysarson Where did you find the error that you report in that issue? I can only find C:\projects\node-test-runner\tests\ci.js: error: tests\*Fail*.elm: expected tests to fail

That is the error - it only manifested after bumping the elm compiler version and went away when I reverted the commit.

> perhaps it would be worthwhile to push a new release 

Yeah, if someone with publish rights has the time that sounds good.

> interim hotfix to just run npm audit fix and push the updated package-lock.json

See https://github.com/rtfeldman/node-test-runner/pull/364#issuecomment-498181808

**Comment by afriestad** [comment]
> That is the error - it only manifested after bumping the elm compiler version and went away when I reverted the commit.

In your bug report in https://github.com/elm/compiler/issues/1937, you mention another error:

```
The process cannot access the file because it is being used by another process.
##[error]Cmd.exe exited with code '1'.
```

This is the one I meant. The CI link you provided in the issue seems to be broken. However, that seems to be related to https://github.com/elm/compiler/issues/1957 and not something I know how to fix or even approach. I can only hope that it and `expected tests to fail` are two different and distinct errors.

> See [#364 (comment)](https://github.com/rtfeldman/node-test-runner/pull/364#issuecomment-498181808)

I am not sure if you agree and disagree with me here. I read https://github.com/rtfeldman/node-test-runner/pull/364#issuecomment-502849743 like this: "`elm@0.19.0-no-deps` currently has issues on Windows, and should not yet be used", so even if that will ultimately be the fix, I still think a "hotfix" is a good way to get rid of the problem without having to wait for `elm/compiler`. There does not seem to be a PR currently working on addressing that, nor any concrete plans for actions in the related issues.

> Yeah, if someone with publish rights has the time that sounds good.

This would be enough for me, as it fixes my original angle coming into this issue :)

**Comment by harrysarson** [comment]
> The CI link you provided in the issue seems to be broken.

Thanks for flagging - I have updated the link to https://harrysarson.visualstudio.com/harrysarson/_build/results?buildId=37.

> I still think a "hotfix" is a good way to get rid of the problem without having to wait for elm/compiler.

"hotfixing" is dangerous as we mess with dependancies of dependancies. The `tar` dep requires a major update to fix the vulnerability and I think if we "hotfix" this major update it will break binwrap.

**Comment by afriestad** [comment]
> "hotfixing" is dangerous as we mess with dependancies of dependancies. The `tar` dep requires a major update to fix the vulnerability and I think if we "hotfix" this major update it will break binwrap.

I absolutely see your point in the general case. However, it is not true that `tar` requires a major update. [The fix was backported](https://www.npmjs.com/advisories/803) to `node-tar@2.2.2`, and as such comprises only a patch-level update compared to `binwrap`'s requirement of `^2.2.1`. The same is true of `fstream`, which is currently at `1.0.11` in master and for which [the earliest fixed version](https://www.npmjs.com/advisories/886) is `1.0.12`. `tar` depends on `^1.0.2`. As long as they do in fact follow semver, updating them should be no problem.

I believe this is why they are fixable through `npm audit fix` – if getting rid of the vulnerabilities requires a major-level update, you have to explicitly `npm install` the new version. I ran the command, which performed these patch-level updates automatically, and the test suite (as triggered by `npm test`) is running perfectly for me on macOS 10.12 with the updated dependencies. I can make a pull request for this tomorrow, if that is desired.

As a side note, dependencies on both [tar](https://github.com/rtfeldman/node-test-runner/blob/23d82f880edbf32b0e1e37b83c0b2064e6970af0/package-lock.json#L120) and [fstream](https://github.com/rtfeldman/node-test-runner/blob/23d82f880edbf32b0e1e37b83c0b2064e6970af0/package-lock.json#L1541) actually use the hat notation in `package-lock.json`, so I am not entirely sure why they didn't automatically download the patched versions.

**Comment by harrysarson** [comment]
See https://github.com/rtfeldman/node-test-runner/issues/415. I think there is nothing further actionable here. Please re-open (or ask me to re-open) if there is more we can do!
