### ISSUE TITLE
Support using elm from node_modules

### ISSUE THREAD

**Issue by jackwilsdon** [rtfeldman/node-test-runner#419]
I couldn't find an existing issue regarding this, but I think it'd be nice to be able to run `elm-test` using the `elm` from `node_modules` without having to pass `--compiler node_modules/.bin/elm` - it leads to a much more portable setup overall.

**Comment by jackwilsdon** [comment]
I see that node already adds the `.bin` folder to `PATH` when running `elm-test` via `scripts` in `package.json`, so this may not actually be an issue.

**Comment by harrysarson** [comment]
@jackwilsdon can you confirm this issue has resolved itself?

**Comment by lydell** [comment]
I’ve noticed this too.

Usually, it feels safe to assume that `npx foo` is just a shortcut for `./node_modules/.bin/foo`. But in the case of elm-test it isn’t!

If you don’t have a global `elm` in your `$PATH`, `./node_modules/.bin/elm` fails, while `npx elm-test` succeeds.

```
$ ./node_modules/.bin/elm-test
Unhandled exception while running the tests: Error: Cannot find elm executable, make sure it is installed.
(If elm is not on your path or is called something different the --compiler flag might help.)
    at Object.<anonymous> (/Users/lydell/test-project/node_modules/elm-test/lib/elm-test.js:102:11)
    at Module._compile (internal/modules/cjs/loader.js:1076:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1097:10)
    at Module.load (internal/modules/cjs/loader.js:941:32)
    at Function.Module._load (internal/modules/cjs/loader.js:782:14)
    at Module.require (internal/modules/cjs/loader.js:965:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/Users/lydell/test-project/sweden/node_modules/elm-test/bin/elm-test:3:1)
    at Module._compile (internal/modules/cjs/loader.js:1076:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1097:10)
    at Module.load (internal/modules/cjs/loader.js:941:32)
    at Function.Module._load (internal/modules/cjs/loader.js:782:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47
```

The reason is because elm-test only supports ./node_modules/.bin/elm implicitly. It just assumes that `elm` is available in `$PATH` if `--compiler` isn’t passed. It works if run via `npx` or `npm run` because `npx`/`npm` adds `./node_modules/.bin` to `$PATH` for the child processes they spawn.

If we want `./node_modules/.bin/elm-test` to work the same as `npx elm-test` we need to find the closest `node_modules` and look for `.bin/elm-test` in there ourselves I think. And make sure that it works correctly on Windows.

**Comment by harrysarson** [comment]
In my (tentative) view running node apps via their path `./node_modules/.bin/elm-test` is a bit of a hack. To solve this issue well we would need to check if this app is run from node_modules and only apply the directory walk up logic if so. It all seems like quite a bit of effort to me (although happy to be convinced otherwise!).

What advantage does  `./node_modules/.bin/elm-test` give over `npm elm-test`?

**Comment by lydell** [comment]
I used to have `./node_modules/.bin` in my `$PATH` so I can run locally installed tools without creating `npm run` scripts, and I used to have no global Elm install – that’s how I found out about it from the beginning.

Since then `npx` has become a thing and after some time I finally started using it instead of my `$PATH` hack. And I also have a global Elm install. So for me personally I don’t care. All this just left me with an unsettled feeling.

It’s a very subtle distinction between `npx foo` and `./node_modules/.bin/foo`. It looks very much they are equivalent, but as evidenced they’re not. It’s really difficult to figure that out, though, and the error message doesn’t help you either.

It’s indeed unclear what the correct solution is and what the benefits are.

Do you have any input, @jackwilsdon ?

**Comment by lydell** [comment]
Maybe we can check if `process.env.PATH` contains `node_modules/.bin` – when it doesn’t, we could extend the error message to mention that you need to run using `npx` or `npm run` or `yarn` or whatever if you want a local Elm installation to be picked up.

On the other hand, I just noticed elm-review works the same way as elm-test:

```
❯ ./node_modules/.bin/elm-review
-- ELM NOT FOUND ---------------------------------------------------------------

I could not find the executable for the elm compiler.

A few options:
- Install it globally
- Specify the path using --compiler <path-to-elm>
```

So it’s not as if elm-test is the odd one out here. Maybe the mere existence of this issue is enough – if somebody else runs into this they might find this and learn about the details.

**Comment by harrysarson** [comment]
In which case I will close as `wont-fix`. If someone has a usecase where running `npx elm-test` does not work then I am happy to re-open and discuss 👍
