### ISSUE TITLE
Feature request: Add line number and input value to output for failed tests

### ISSUE THREAD

**Issue by szTheory** [rtfeldman/node-test-runner#428]
It could be on by default, or through a command-line argument. This way you can quickly click on the filename/line number in VS Code to jump to the failing test. And by having the input that the test failed on, you could diagnose what happened without having to look up the spec in the first place.

Here's an example of what failing test output looks like today, without the filename/line number or input for the failed test.

```
↓ Tests
↓ Bob
✗ stating something

    "Fine. Be that way!"
    ╷
    │ Expect.equal
    ╵
    "Whatever."
```

**Comment by harrysarson** [comment]
This is a really cool idea. It would need compiler support though so unlikely to happen in the short term. 

With my tidying up this repository apron on I think this issue would be better placed in https://github.com/elm-explorations/test/issues (as it is to do with the test creation itself rather than the running of tests) . Would it be possible to re-open there?

**Comment by szTheory** [comment]
Re-opened at https://github.com/elm-explorations/test/issues/152
