### ISSUE TITLE
Ban the flow `any` type.

### ISSUE THREAD

**Issue by harrysarson** [rtfeldman/node-test-runner#478]
There’s [eslint-plugin-flowtype/no-weak-types](https://github.com/gajus/eslint-plugin-flowtype#no-weak-types). 

1. I could install that plugin.
2. Enable the rule in our flow config.
3. Confirm it works by changing a type alias to `any` somewhere and checking that CI fails.

Thanks for the suggestion for this issue @lydell :)

**Comment by lydell** [comment]
> Enable the rule in our flow config.

Just to clarify, we would enable it in `.eslintrc.json` (not `.flowconfig`).

In `.flowconfig` we actually have `unclear-type=off`. An alternative would be to enable _that_ instead. I suspect that’s harder since the ESLint rule only warns about explicit `any` annotations, while the Flow rule warns about inferred `any` types as well.

**Comment by lydell** [comment]
Turns out the code base has cleaned up a lot since last time I touched `.flowconfig` – enabling `unclear-type` only caused 2 errors that were easy to fix so I went ahead and did that: [`43b76cc` (#475)](https://github.com/rtfeldman/node-test-runner/pull/475/commits/43b76cc15b2c0b69941c30cb06a3bd4edf77c26d)

**Comment by harrysarson** [comment]
Wow, nice work
