### ISSUE TITLE
Add support for darwin-arm64

### ISSUE THREAD

**Issue by czepluch** [rtfeldman/node-test-runner#484]
I just got my hands on an Apple Silicon based macbook, and after installing nvm and compiling the newest version of node I get the following error when trying to install `elm-test`:

```
Error: No binaries are available for your platform: darwin-arm64
```

**Comment by lydell** [comment]
Hi! I think this won’t happen on the master branch. Can you try it? Something like this:

```
npm install --save-dev rtfeldman/node-test-runner
npx elm-test
```

**Comment by czepluch** [comment]
Still getting the same error when trying above. Maybe I can just install an older non-arm version of npm and then run the Rosetta translated version.

**Comment by harrysarson** [comment]
Can you install elm-json?

**Comment by lydell** [comment]
Ah, shoot. That’s because when you install from GitHub, npm also install all _dev_ dependencies. And in  our dev dependencies we have elm-review, which eventually depends on the binwrap package which is where “No binaries are available for your platform” message comes from.

A new version of elm-review was just released though which no longer depends on binwrap, so if we update to that version I think `npm install --save-dev rtfeldman/node-test-runner` will start working.

**Comment by lydell** [comment]
I made a pull request: https://github.com/rtfeldman/node-test-runner/pull/485

@czepluch Can you try installing from the PR?

```
npm i --save-dev lydell/node-test-runner#update-elm-review
```

**Comment by czepluch** [comment]
> Can you install elm-json?

Yes.

> npm i --save-dev lydell/node-test-runner#update-elm-review

Worked!

**Comment by harrysarson** [comment]
Now fixed on master. Thanks for the report :)

**Comment by czepluch** [comment]
Thanks for the quick response :D
