### ISSUE TITLE
Idea: interactive mode

### ISSUE THREAD

**Issue by rtfeldman** [rtfeldman/node-test-runner#91]
What if you could run `elm-test --interactive` and when it got to a test failure, it could ask you if you'd like to jump into a REPL session right there to debug?

The time-saving feature would be that everything inside the test's anonymous function would be in scope (plus the file's toplevel scope as usual), so you could play around with maximum ease.

I don't know how often that would actually come in handy, and it sounds like it'd take a lot of work, but it's an idea!

Maybe https://github.com/shamansir/node-elm-repl would be useful?

**Comment by zkessin** [comment]
that sounds very cool, not sure how often I would actually use it

**Comment by jhutchins** [comment]
The python test runner nose has this feature and it's one of my favorite (http://nose.readthedocs.io/en/latest/usage.html#cmdoption--pdb). In that environment I found it to be a very useful feature in practice, but only because I could step up through the stack trace and see the state in those various contexts so I could determine where the state went wrong. In Elm I think a feature like this could be very useful, but only if there was some ability to step back through history in the REPL, which I imagine would be quite the undertaking.

**Comment by rtfeldman** [comment]
This is a cool idea for the indefinitely far future. Gonna close it for now.
